name: AWS example workflow

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  BUCKET_NAME: "terraform-test-us-east-2"   # cámbialo por uno único
  AWS_REGION:  "us-east-2"

permissions:
  id-token: write
  contents: read

jobs:
  S3PackageUpload:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v5

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: samplerolesession
          aws-region: ${{ env.AWS_REGION }}

      # Crea el bucket si no existe (idempotente)
      - name: Ensure bucket exists
        env:
          BUCKET_NAME: ${{ env.BUCKET_NAME }}
          AWS_REGION:  ${{ env.AWS_REGION }}
        run: |
          set -e
          if aws s3api head-bucket --bucket "$BUCKET_NAME" 2>/dev/null; then
            echo "Bucket $BUCKET_NAME already exists"
          else
            echo "Creating bucket $BUCKET_NAME in $AWS_REGION..."
            if [ "$AWS_REGION" = "us-east-1" ]; then
              aws s3api create-bucket --bucket "$BUCKET_NAME"
            else
              aws s3api create-bucket --bucket "$BUCKET_NAME" \
                --create-bucket-configuration LocationConstraint="$AWS_REGION"
            fi
          fi

      - name: Copy index.html to S3
        run: aws s3 cp ./index.html "s3://${{ env.BUCKET_NAME }}/"
