name: terraform-min
on:
  push: { branches: [ "main" ] }
  workflow_dispatch: {}

jobs:
  apply:
    runs-on: ubuntu-latest
    permissions: { id-token: write, contents: read }   # OIDC
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with: { terraform_version: 1.6.6 }

      - name: Configure AWS creds (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: Terraform Init
        working-directory: infra
        run: terraform init -input=false

      - name: Terraform Apply (auto)
        working-directory: infra
        run: terraform apply -auto-approve -input=false
